import pdfplumber
from openai import AzureOpenAI
client = AzureOpenAI(
    api_key="",
    api_version="",
    azure_endpoint=""
)
def extract_text_from_pdf(pdf_path):
    text = ""
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            text += page.extract_text() + "\n"
    return text.strip()



# pdf_path = r"C:\Users\rohan.rf\PycharmProjects\PythonProject\Profile.pdf"
pdf_path=r"C:\Users\rohan.rf\PycharmProjects\PythonProject\Siddarth Resume 1.pdf"

try:
    resume_text = extract_text_from_pdf(pdf_path)
    print("Successfully extracted text from PDF.")
except Exception as e:
    print(f"Error extracting text from PDF: {e}")
    exit()


prompt = f"""
You are an expert AI trained to distinguish between human-written and AI-generated resumes. Analyze the following resume and determine the likelihood that it was generated by an AI.

Evaluate the resume using the following criteria:

1. **Language Patterns**:
   - Is the language overly generic, polished, or formal?
   - Are there signs of repetitive or templated sentence structures?
   - Does the vocabulary lack natural variation or sound unnatural?

2. **Content Specificity**:
   - Are there concrete, personal, or quantifiable achievements?
   - Does the resume reflect realistic career progression and domain-specific knowledge?

3. **Stylistic Consistency**:
   - Is the tone consistent throughout the document?
   - Are there formatting inconsistencies or signs of automated generation?

4. **Comparative Analysis**:
   - Highlight any phrases or sections that resemble known AI-generated content.
   - Compare the structure and phrasing to patterns you would typically generate.

5. **Training Data Comparison**:
   - Cross-reference the resume’s language, structure, and phrasing with examples of AI-generated resumes from your training data.
   - Identify any strong similarities or direct matches to known AI-generated resume templates or phrasing.

Then provide the following in a structured format:
- **Mention Ai-generated or Human Written 
- **Confidence Score (0–100%)**: Likelihood that the resume was AI-generated
- **Highlighted Examples**: Specific excerpts that support your conclusion
- **Reasoning**: A concise explanation based on your internal knowledge of AI generation patterns and training data comparisons

Resume Text:
{resume_text}

"""


try:
    response = client.chat.completions.create(
        model="synapt-dev-gpt-4o-mini",
        messages=[
            {"role": "system", "content": "Your task is to determine whether the given resume is AI-generated."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.3,
        max_tokens=300
    )


    print("\nAnalysis Results:")
    print( response.choices[0].message.content)

except Exception as e:
    print(f"Error calling Azure OpenAI: {e}")
